In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,roc_auc_score,classification_report

In [80]:
data=load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [81]:
X=data.data
y=data.target
X,y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [82]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [83]:
Scaler=StandardScaler()
X_train_scale=Scaler.fit_transform(X_train)
X_test_scale=Scaler.transform(X_test)

In [84]:
lr=LogisticRegression(penalty='l1',solver='liblinear',C=1.0)
lr.fit(X_train_scale,y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [85]:
dt=DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [86]:
rf=RandomForestClassifier(random_state=50,n_estimators=50)
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50, random_state=50)

In [87]:
lr_pred=lr.predict(X_test_scale)
dt_pred=dt.predict(X_test)
rf_pred=rf.predict(X_test)

In [88]:
lr_prob=lr.predict_proba(X_test_scale)[:,1]
dt_prob=dt.predict_proba(X_test)[:,1]
rf_prob=rf.predict_proba(X_test)[:,1]

In [89]:
def evaluate_model(name,y_test,y_pred,y_prob):
  print(f"\n{name} Evaluation")
  print("accuracy_score:",accuracy_score(y_test,y_pred))
  print("precision score:",precision_score(y_test,y_pred))
  print("recall score:",recall_score(y_test,y_pred))
  print("f1 score:",f1_score(y_test,y_pred))
  print("ROC-AUC :",roc_auc_score(y_test,y_prob))
  print("confusion matrix:\n",confusion_matrix(y_test,y_pred))
  print("Classification report:\n",classification_report(y_test,y_pred))

In [90]:
evaluate_model("Logistic Regression",y_test,lr_pred,lr_prob)
evaluate_model("Decision Tree",y_test,dt_pred,dt_prob)
evaluate_model("Random Forest",y_test,rf_pred,rf_prob)


Logistic Regression Evaluation
accuracy_score: 0.9736842105263158
precision score: 0.9857142857142858
recall score: 0.971830985915493
f1 score: 0.9787234042553191
ROC-AUC : 0.9967245332459876
confusion matrix:
 [[42  1]
 [ 2 69]]
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.98      0.97        43
           1       0.99      0.97      0.98        71

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114


Decision Tree Evaluation
accuracy_score: 0.9473684210526315
precision score: 0.9577464788732394
recall score: 0.9577464788732394
f1 score: 0.9577464788732394
ROC-AUC : 0.9439895185063871
confusion matrix:
 [[40  3]
 [ 3 68]]
Classification report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93        43
           1       0.96      0.96      0.96        71

    